name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate snake.svg
      uses: Platane/snk@v2
      with:
        github_user_name: Atome1212  # Assurez-vous que c'est bien votre nom d'utilisateur GitHub
        output: dist/snake.svg  # Correction de la clé "output" au lieu de "outputs"

    - name: Commit and Push
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add dist/snake.svg
        git commit -m "Generate snake.svg"
        git push origin main
