name: Generate Snake

on:
  schedule: 
    - cron: "0 0 * * *" # runs at midnight every day
  workflow_dispatch: # Allows you to manually trigger the workflow from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy Snake
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: images
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
