  name: Generate Snake

on:
  schedule: 
    - cron: "0 0 * * *" # runs at midnight every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Snake
        run: |
          docker run \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -v $(pwd):/app \
            platane/snk generate \
            --user Atome1212 \
            --output ./images/github-contribution-grid-snake.svg
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: images
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
