name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Generate snake.svg
      uses: Platane/snk@v2
      with:
        github_user_name: Atome1212

    - name: Commit and Push
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add images/github-contribution-grid-snake.svg
        git commit -m "Generate snake.svg"
        git push origin main
